#!/bin/bash
set -e  # Exit on any error

echo "🚀 Full Stack Deployment Script"
echo "================================="
echo ""

# Check we're in the right directory (root)
if [ ! -f "package.json" ] || [ ! -d "frontend" ] || [ ! -d "backend" ]; then
  echo "❌ Error: Must run from project root directory"
  exit 1
fi

# Build the frontend
echo "📦 Building PureScript frontend..."
cd frontend
make build
cd ..

# Check if built files exist
if [ ! -f "frontend/public/bundle.js" ]; then
  echo "❌ Error: bundle.js not generated"
  exit 1
fi

if [ ! -f "frontend/public/styles.css" ]; then
  echo "❌ Error: styles.css not generated"
  exit 1
fi

echo "✅ Frontend build complete"
echo ""

# Show bundle size
BUNDLE_SIZE=$(du -h frontend/public/bundle.js | cut -f1)
CSS_SIZE=$(du -h frontend/public/styles.css | cut -f1)
echo "📊 Bundle size: $BUNDLE_SIZE"
echo "📊 CSS size: $CSS_SIZE"
echo ""

# Add built files to git
echo "📝 Staging built frontend files..."
git add frontend/public/bundle.js frontend/public/styles.css

# Check if there are changes to commit
if git diff --cached --quiet; then
  echo "ℹ️  No changes to built files, skipping commit"
else
  echo "💾 Committing built files..."
  git commit -m "Build PureScript frontend for deployment

Bundle: $BUNDLE_SIZE
CSS: $CSS_SIZE

🤖 Generated by deploy.sh"
fi

echo ""
echo "🎯 Ready to deploy!"
echo ""
echo "Next steps:"
echo "  1. Push to your branch: git push origin $(git branch --show-current)"
echo "  2. Deploy to Heroku: git push heroku $(git branch --show-current):master"
echo ""
echo "Heroku will build both frontend and backend on deployment."
echo ""
echo "Or run this now:"
echo "  git push heroku $(git branch --show-current):master"
echo ""

read -p "Deploy to Heroku now? (y/N) " -n 1 -r
echo
if [[ $REPLY =~ ^[Yy]$ ]]; then
  echo "🚀 Deploying to Heroku..."
  git push heroku $(git branch --show-current):master

  echo ""
  echo "✅ Deployment complete!"
  echo "📱 Opening app..."
  heroku open
else
  echo "👍 Skipping Heroku deploy"
fi
